language: php
php:
  - 5.3
#  - 5.4

env:
  - DB=mysql TYPO3=master INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-1 INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_6-0 INTEGRATION=master
  - DB=mysql TYPO3=TYPO3_4-7 INTEGRATION=TYPO3_4-7
  - DB=mysql TYPO3=TYPO3_4-6 INTEGRATION=TYPO3_4-7
  - DB=mysql TYPO3=TYPO3_4-5 INTEGRATION=TYPO3_4-7

#matrix:
#  include:
#    - php: 5.5
#      env: DB=mysql TYPO3=master INTEGRATION=master

before_script:
  - sudo apt-get update && sudo apt-get install git
# Install build dependencies
  - cd ..
  - git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/Apen/TYPO3-Travis-Integration.git build-environment
  - git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
  - installPhpModule -y memcache
  - installPhpModule redis
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone --single-branch --branch $TYPO3 --depth 1 git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv core/typo3 .
  - if [[ -d core/t3lib ]]; then mv core/t3lib . ; fi
  - mv build-environment/typo3conf .
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mv additional_reports ./typo3conf/ext
  - git clone --single-branch --branch master --depth 1 git://git.typo3.org/TYPO3v4/Extensions/tt_news.git typo3conf/ext/tt_news/
  #- mkdir fileadmin
  #- mkdir uploads
  #- mkdir typo3temp
  - mv build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Files/fileadmin .
  - mv build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Files/uploads .
  - mv build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Files/typo3temp .
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/phpunit.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/phpunit.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/typo3-45-cache-extensions.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/typo3-45-cache-extensions.sql; fi
  - if [[ "$DB" == "mysql" && -f build-environment/dbimport/typo3-6-cache-extensions.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/typo3-6-cache-extensions.sql; fi

script:
  - /usr/bin/env php typo3/cli_dispatch.phpsh phpunit --colors --debug typo3conf/ext/additional_reports
